config {
  type: "table",
  name: "rpt_nba_players_summary",
  schema: "dataform",
  tags: ["nba", "marts", "daily"],
  assertions: {
    uniqueKey: ["season"],
    nonNull: ["avg_age"]
  },
  dependOnDependencyAssertions: true,
  dependencies: ["fct_nba_players"]
}

SELECT
  season,
  COUNT(DISTINCT player) AS player_count,
  AVG(age) AS avg_age,
  AVG(height_cm) AS avg_height,
  AVG(weight_kg) AS avg_weight
FROM ${ref("fct_nba_players")}
GROUP BY season
